import { loadEnvConfig } from "@next/env";
const projectDir = process.cwd();
loadEnvConfig(projectDir);

import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { sql, eq } from "drizzle-orm";
import fs from "fs";
import path from "path";
import { faker } from "@faker-js/faker";

import * as schema from "../schema";

if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is not defined. Check your .env.local file.");
}

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: process.env.DATABASE_URL.includes("neon.tech")
        ? { rejectUnauthorized: false }
        : false,
    max: 1,
});

const db = drizzle(pool, { schema });

const seedAuth = betterAuth({
    database: drizzleAdapter(db, {
        provider: "pg",
        schema: {
            ...schema,
            user: schema.user,
            session: schema.session,
            account: schema.account,
        },
    }),
    emailAndPassword: {
        enabled: true,
    },
});

const getRandomWallet = () => {
    const wallets = ["", ""]; // add wallet address here (Sepolia)
    return faker.helpers.arrayElement(wallets);
};

const getRandomCardBrand = () => {
    return faker.helpers.arrayElement([
        "visa",
        "mastercard",
        "amex",
        "discover",
    ]);
};

async function clearDatabase() {
    console.log("🗑️  Emptying existing data...");
    await db.execute(
        sql`TRUNCATE TABLE "orders", "messages", "items", "account", "session", "user" RESTART IDENTITY CASCADE;`,
    );
}

async function main() {
    console.log("🚀 Starting database seed for Users...");

    try {
        await clearDatabase();

        console.log(
            "⚙️  Generating 100 fake users and inserting them into the database...",
        );

        // This array will hold the users with their actual Database IDs
        const finalUsers = [];

        for (let i = 0; i < 100; i++) {
            const email = faker.internet.email();
            const password = faker.internet.password({ length: 14 });
            const name = faker.person.fullName();
            const image = `https://i.pravatar.cc/300?u=${encodeURIComponent(email)}`;
            const cryptoWalletAddress = getRandomWallet();
            const savedCardBrand = getRandomCardBrand();
            const savedCardLast4 = faker.string.numeric(4);

            try {
                // 1. Insert user via Better Auth FIRST
                const res = await seedAuth.api.signUpEmail({
                    body: {
                        email,
                        password,
                        name,
                        image,
                    },
                });

                // 2. Extract the real ID generated by Better Auth
                if (res?.user?.id) {
                    const realDatabaseId = res.user.id;

                    // 3. Update the newly created user with the extra custom fields
                    await db
                        .update(schema.user)
                        .set({
                            cryptoWalletAddress,
                            savedCardBrand,
                            savedCardLast4,
                        })
                        .where(eq(schema.user.id, realDatabaseId));

                    // 4. Push the completed user (with the REAL ID) to our final array
                    finalUsers.push({
                        id: realDatabaseId,
                        name,
                        email,
                        password,
                        image,
                        cryptoWalletAddress,
                        savedCardBrand,
                        savedCardLast4,
                    });
                }
            } catch (err) {
                console.warn(`⚠️  Failed to create user ${email}:`, err);
            }
        }

        // 5. Write the finalized data to users.json at the VERY END
        const filePath = path.join(__dirname, "users.json");
        fs.writeFileSync(
            filePath,
            JSON.stringify({ users: finalUsers, items: [] }, null, 2),
        );
        console.log("💾 Saved generated user data to users.json");

        // Clean up any active sessions Better Auth created during the sign-up process
        await db.delete(schema.session);

        console.log("✅ User seed completed successfully!");
    } catch (error) {
        console.error("❌ Seed failed:", error);
        process.exit(1);
    } finally {
        await pool.end();
    }
}

main();
