import { loadEnvConfig } from "@next/env";
loadEnvConfig(process.cwd());

import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { sql, eq } from "drizzle-orm";
import fs from "fs";
import path from "path";
import { faker } from "@faker-js/faker";

import * as schema from "../schema";

if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is not defined. Check your .env.local file.");
}

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: process.env.DATABASE_URL.includes("neon.tech")
        ? { rejectUnauthorized: false }
        : false,
    max: 1,
});

const db = drizzle(pool, { schema });

const seedAuth = betterAuth({
    database: drizzleAdapter(db, {
        provider: "pg",
        schema: {
            ...schema,
            user: schema.user,
            session: schema.session,
            account: schema.account,
        },
    }),
    emailAndPassword: {
        enabled: true,
    },
});

const getRandomWallet = () => {
    const wallets = ["", ""]; // add wallet address here (Sepolia)
    return faker.helpers.arrayElement(wallets);
};

const getRandomCardBrand = () => {
    return faker.helpers.arrayElement([
        "visa",
        "mastercard",
        "amex",
        "discover",
    ]);
};

async function clearDatabase() {
    console.log("🗑️  Emptying existing data...");
    await db.execute(
        sql`TRUNCATE TABLE "orders", "messages", "items", "account", "session", "user" RESTART IDENTITY CASCADE;`,
    );
}

async function fetchRandomUsers(targetCount) {
    console.log(`🌐 Fetching users from Random User API...`);

    // Fetch double the target to ensure we have enough buffer after filtering out bad names
    const fetchCount = targetCount * 2;

    // The 'nat' parameter restricts to US, GB, CA, and AU to reduce non-Latin characters at the API level
    const res = await fetch(
        `https://randomuser.me/api/?results=${fetchCount}&nat=us,gb,ca,au`,
    );
    const data = await res.json();

    if (!data || !data.results) {
        console.warn("⚠️  Invalid data received from Random User API.");
        return [];
    }

    const uniqueUsersMap = new Map();

    // Regex allows standard A-Z, spaces, hyphens (e.g., Mary-Jane), and apostrophes (e.g., O'Connor)
    const englishCharsOnly = /^[a-zA-Z\s\-']+$/;

    for (const user of data.results) {
        const fullName = `${user.name.first} ${user.name.last}`;

        // Strict Check: Name must pass regex AND email must be unique
        if (
            englishCharsOnly.test(fullName) &&
            user.email &&
            !uniqueUsersMap.has(user.email)
        ) {
            uniqueUsersMap.set(user.email, {
                email: user.email,
                name: fullName,
                password: user.login.password,
                avatar: user.picture.large,
            });
        }

        // Stop the loop exactly when we hit our target of 100
        if (uniqueUsersMap.size === targetCount) {
            break;
        }
    }

    const uniqueUsers = Array.from(uniqueUsersMap.values());
    console.log(
        `✅ Collected ${uniqueUsers.length} clean, English-named users.`,
    );
    return uniqueUsers;
}

async function main() {
    console.log("🚀 Starting database seed for Users...");

    try {
        await clearDatabase();

        const fakeUsers = await fetchRandomUsers(100);

        console.log(
            `⚙️  Inserting ${fakeUsers.length} users into the database...`,
        );

        const finalUsers = [];

        for (const apiUser of fakeUsers) {
            const email = apiUser.email;
            const name = apiUser.name;
            const image = apiUser.avatar;

            const password =
                apiUser.password && apiUser.password.length >= 8
                    ? apiUser.password
                    : faker.internet.password({ length: 14 });

            const cryptoWalletAddress = getRandomWallet();
            const savedCardBrand = getRandomCardBrand();
            const savedCardLast4 = faker.string.numeric(4);

            try {
                // 1. Insert user via Better Auth FIRST
                const res = await seedAuth.api.signUpEmail({
                    body: {
                        email,
                        password,
                        name,
                        image,
                    },
                });

                // 2. Extract the real ID generated by Better Auth
                if (res?.user?.id) {
                    const realDatabaseId = res.user.id;

                    // 3. Update the newly created user with the extra custom fields
                    await db
                        .update(schema.user)
                        .set({
                            cryptoWalletAddress,
                            savedCardBrand,
                            savedCardLast4,
                        })
                        .where(eq(schema.user.id, realDatabaseId));

                    // 4. Push the completed user to our final array
                    finalUsers.push({
                        id: realDatabaseId,
                        name,
                        email,
                        password,
                        image,
                        cryptoWalletAddress,
                        savedCardBrand,
                        savedCardLast4,
                    });
                }
            } catch (err) {
                console.warn(
                    `⚠️  Failed to create user ${email}:`,
                    err.message || err,
                );
            }
        }

        // 5. Write the finalized data to users.json
        const filePath = path.join(__dirname, "users.json");
        fs.writeFileSync(
            filePath,
            JSON.stringify({ users: finalUsers, items: [] }, null, 2),
        );
        console.log(
            `💾 Saved ${finalUsers.length} generated user(s) to ${filePath}`,
        );

        // Clean up any active sessions Better Auth created during the sign-up process
        await db.delete(schema.session);

        console.log("✅ User seed completed successfully!");
    } catch (error) {
        console.error("❌ Seed failed:", error);
        process.exit(1);
    } finally {
        await pool.end();
    }
}

main();
